core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('store.urls', namespace="store")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

store/urls.py
from django.urls import path 
from .views import (CheckoutView, ItemDetail, HomeView, add_to_cart, 
                    remove_from_cart, OrderSummaryView, remove_single_item_from_cart,
                    PaymentView, AddCouponView, RequestRefundView, CategoryDetail,
                    LandingPage
)
app_name = "store"

urlpatterns = [
    path("", LandingPage, name="landpage"),
    path("home/", HomeView.as_view(), name="home"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("order-summary/", OrderSummaryView.as_view(), name="order-summary"),
    path("product/<slug>", ItemDetail.as_view(), name="product"),
    path("add-to-cart/<slug>", add_to_cart, name="add-to-cart"),
    path("add-coupon", AddCouponView.as_view(), name="add-coupon"),
    path("remove-from-cart/<slug>", remove_from_cart, name="remove-from-cart"),
    path("remove-single-item-from-cart/<slug>", remove_single_item_from_cart, name="remove-single-item-from-cart"),
    path("payment/<payment_option>", PaymentView.as_view(), name="payment"),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),

    path('categorydetail/<slug>', CategoryDetail, name='categorydetail')
]

store/models.py
from django.db.models.signals import post_save
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField

# Create your models here.
CATEGORY_CHOICES = (
    ('I', 'Import Cars'),
    ('BF', 'Baby Food'),
    ('F', 'Furniture')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


# class UserProfile(models.Model):
#     user = models.OneToOneField(
#         settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
#     one_click_purchasing = models.BooleanField(default=False)

#     def __str__(self):
#         return self.user.username

class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to="static/img/product_images/, blank=True", null= True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('store:product', kwargs={'slug': self.slug})

    def get_add_to_cart_url(self):
        return reverse('store:add-to-cart', kwargs={ 'slug': self.slug })

    def get_remove_from_cart_url(self):
        return reverse('store:remove-from-cart', kwargs={ 'slug': self.slug })

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)


    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)


    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()

        if self.coupon:
            total -= self.coupon.amount

        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"



# def userprofile_receiver(sender, instance, created, *args, **kwargs):
#     if created:
#         userprofile = UserProfile.objects.create(user=instance)


# post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}{% endblock %}

    <!-- Bootstrap Css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Link Swiper's CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css"/>
    <!-- Personal Style -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
    
</head>

<body class="bg-light">
  {% include "components/navbar.html" %}

  <div>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
  </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "components/footer.html" %}
    {% include "components/scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}

</body>
</html>

templates/category.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<section class="">
    <div class="container px-4 px-lg-5 mt-4">
        <p class="text-center fw-bold fs-3 mb-3">Category</p>
        <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-3 row-cols-xl-3 ">
          {% for item in category %}
            <div class="col mb-5">
                <div class="card h-100 border-0 shadow overflow-hidden" style="border-radius: 1rem;">
                    <img class="card-img-top img-fluid" src="{{item.image.url}}" alt="..."  style="height: 15rem; object-fit: contain;"/>
                    <div class="card-body p-4" >
                        <div class="text-center">
                          <span>{{item.get_category_display}}</span>
                          <h5>
                            <strong>
                              <p href="{{item.get_absolute_url}}" class="text-dark">{{item.title}}
                                <span class="badge rounded-pill bg-{{item.get_label_display}}">NEW</span>
                              </p>
                            </strong>
                          </h5>
                            <h6 class="font-weight-bold blue-text">
                              <span>$
                                {% if item.discount_price %}
                                  {{item.discount_price}}
                                {% else %}
                                  {{item.price}}
                                {% endif %}
                              </span>
                            </h6>
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto rounded-pill" href="{{item.get_absolute_url}}">View Details</a></div>
                    </div>
                </div>
            </div>
          {% endfor %}
        </div>
    </div>
</section>
        
{% endblock content %}
    

templates/home.html
{% extends 'base.html' %}


{% block content %}
  <!--Main layout-->
  <main>
    <div class="container">

<section class="">
    <div class="container px-5 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-2 row-cols-1 row-cols-md-3 row-cols-xl-4 ">
          {% for item in items %}
            <div class="col mb-5">
                <div class="card h-100 border-0 shadow-sm overflow-hidden" style="border-radius: 1rem;">
                    <img class="card-img-top img-fluid" src="{{item.image.url}}" alt="..."  style="height: 10rem; object-fit: contain;"/>
                    <div class="card-body p-4" >
                        <div class="text-center">
                          <span>{{item.get_category_display}}</span>
                          <h5>
                            <strong>
                              <p href="{{item.get_absolute_url}}" class="text-dark">{{item.title}}
                                <span class="badge rounded-pill bg-{{item.get_label_display}}">NEW</span>
                              </p>
                            </strong>
                          </h5>
                            <h6 class="font-weight-bold blue-text">
                              <span>$
                                {% if item.discount_price %}
                                  {{item.discount_price}}
                                {% else %}
                                  {{item.price}}
                                {% endif %}
                              </span>
                            </h6>
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto rounded-pill" href="{{item.get_absolute_url}}">View Details</a></div>
                    </div>
                </div>
            </div>
          {% endfor %}
        </div>
    </div>
</section>



      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}
    

templates/landingPage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% include 'components/header.html' %}

    <!-- what we offer -->
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row row-cols-1 row-cols-lg-3 g-2 gx-lg-5">

            <div class="col rounded">
                <div class="d-flex align-items-center p-4 shadow">
                    <div class="flex-shrink-0">
                        <i class="bi bi-truck fs-1"></i>
                    </div>
                    <div class="flex-grow-1 ms-3">
                        <span><b>Free Shipping</b></span>
                        <p>Free shipping and delivery on all US order or order above $200 </p>
                    </div>
                </div>
            </div>
            <div class="col rounded">
                <div class="d-flex align-items-center p-4 shadow">
                    <div class="flex-shrink-0">
                        <i class="bi bi-ubuntu fs-1"></i>
                    </div>
                    <div class="flex-grow-1 ms-3">
                        <span><b>Shop with Confidence</b></span>
                        <p>Our Protection covers your purchase from click to delivery</p>
                    </div>
                </div>
            </div>
            <div class="col rounded">
                <div class="d-flex align-items-center p-4 shadow">
                    <div class="flex-shrink-0">
                        <i class="bi bi-telephone-forward-fill fs-1"></i>
                    </div>
                    <div class="flex-grow-1 ms-3">
                        <span><b>24/7 Help Center</b></span>
                        <p>Round-the-clock assistance for a smooth shopping experience</p>
                    </div>
                </div>
            </div>

        </div>
    </div>


    <!-- Section category-->
    <section class="pt-5">
        <div class="container px-4 px-lg-5 mt-5">
            <p class="text-center fw-bold fs-3 mb-3">Category</p>
            <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-3 row-cols-xl-2 justify-content-center">
                <div class="col mb-5">
                    <div class="card h-100 border-0 shadow-sm overflow-hidden" style="border-radius: 1rem;">
                        <!-- Product image-->
                        <img class="card-img-top img-fluid" src="{% static 'img/category/container.jpeg' %}" alt="..."  style="height: 15rem; object-fit: cover;"/>
                        <!-- Product details-->
                        <div class="card-body p-4" >
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">Car Importation</h5>
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto rounded-pill" href="{% url 'store:categorydetail' 'I' %}">View options</a></div>
                        </div>
                    </div>
                </div>
                <div class="col mb-5">
                    <div class="card h-100 border-0 shadow-sm overflow-hidden" style="border-radius: 1rem;">
                        <!-- Product image-->
                        <img class="card-img-top img-fluid" src="static/img/category/baby-food.jpeg" alt="..."  style="height: 15rem; object-fit: cover;"/>
                        <!-- Product details-->
                        <div class="card-body p-4" >
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">Baby Food In Wholesales</h5>
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto rounded-pill" href="{% url 'store:categorydetail' 'BF' %}">View options</a></div>
                        </div>
                    </div>
                </div>
                <div class="col mb-5">
                    <div class="card h-100 border-0 shadow-sm overflow-hidden" style="border-radius: 1rem;">
                        <!-- Product image-->
                        <img class="card-img-top img-fluid" src="static/img/category/furniture.jpeg" alt="..."  style="height: 15rem; object-fit: cover;"/>
                        <!-- Product details-->
                        <div class="card-body p-4" >
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">Furniture  Importation</h5>
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto rounded-pill" href="{% url 'store:categorydetail' 'F' %}">View options</a></div>
                        </div>
                    </div>
                </div>
                <div class="col mb-5">
                    <div class="card h-100 border-0 shadow-sm overflow-hidden" style="border-radius: 1rem;">
                        <!-- Product image-->
                        <img class="card-img-top img-fluid" src="static/img/category/fund.jpeg" alt="..."  style="height: 15rem; object-fit: cover;"/>
                        <!-- Product details-->
                        <div class="card-body p-4" >
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">Money Changer</h5>
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto rounded-pill" href="#">View options</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Testimonial -->
        <p class="text-center fw-bold fs-3">Testimonial</p>
    <section class="content">
        <div class="testimonial mySwiper2">
            <div class="testi-content swiper-wrapper">
            <div class="slide swiper-slide">
                <img src="static/img/bg1.png" alt="" class="image shadow-lg" />
                <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam,
                saepe provident dolorem a quaerat quo error facere nihil deleniti
                eligendi ipsum adipisci, fugit, architecto amet asperiores
                doloremque deserunt eum nemo.
                </p>

                <i class="bx bxs-quote-alt-left quote-icon"></i>

                <div class="details">
                <span class="name">Marnie Lotter</span>
                <span class="job">Web Developer</span>
                </div>
            </div>
            <div class="slide swiper-slide">
                <img src="static/img/bg1.png" alt="" class="image shadow-lg" />
                <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam,
                saepe provident dolorem a quaerat quo error facere nihil deleniti
                eligendi ipsum adipisci, fugit, architecto amet asperiores
                doloremque deserunt eum nemo.
                </p>

                <i class="bx bxs-quote-alt-left quote-icon"></i>

                <div class="details">
                <span class="name">Marnie Lotter</span>
                <span class="job">Web Developer</span>
                </div>
            </div>
            <div class="slide swiper-slide">
                <img src="static/img/bg1.png" alt="" class="image shadow-lg" />
                <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam,
                saepe provident dolorem a quaerat quo error facere nihil deleniti
                eligendi ipsum adipisci, fugit, architecto amet asperiores
                doloremque deserunt eum nemo.
                </p>

                <i class="bx bxs-quote-alt-left quote-icon"></i>

                <div class="details">
                <span class="name">Marnie Lotter</span>
                <span class="job">Web Developer</span>
                </div>
            </div>
            </div>
            <div class="swiper-button-next nav-btn"></div>
            <div class="swiper-button-prev nav-btn"></div>
            <div class="swiper-pagination"></div>
        </div>
    </section>
{% endblock content %}
    

{% block extra_scripts %}

<script>

    var swiper = new Swiper(".mySwiper2", {
        slidesPerView: 1,
        grabCursor: true,
        loop: true,
        pagination: {
            el: ".swiper-pagination",
            clickable: true,
        },
        navigation: {
            nextEl: ".swiper-button-next",
            prevEl: ".swiper-button-prev",
        },
        autoplay: {
            delay: 5000,
        },
    });

</script>

{% endblock extra_scripts %}

templates/order_snippet.html
<div class="col-md mb-4">

<!-- Heading -->
<h4 class="d-flex justify-content-between align-items-center mb-3">
<span class="text-muted">Your cart</span>
<span class="badge badge-secondary badge-pill">{{order.items.count}}</span>
</h4>

<!-- Cart -->
<ul class="list-group mb-3 z-depth-1">
{% for order_item in order.items.all %}
<li class="list-group-item d-flex justify-content-between lh-condensed">
    <div>
    <h6 class="my-0">{{order_item.quantity}} x {{order_item.item.title}}</h6>
    <small class="text-muted">{{order_item.item.description}} </small>
    </div>
    <span class="text-muted">${{order_item.get_final_price}}</span>
</li>
{% endfor %}
{% if order.coupon %}
<li class="list-group-item d-flex justify-content-between bg-light">
    <div class="text-success">
    <h6 class="my-0">Promo code</h6>
    <small>{{order.coupon.code}}</small>
    </div>
    <span class="text-success">-${{order.coupon.amount}}</span>
</li>
{% endif %}
<li class="list-group-item d-flex justify-content-between">
    <span>Total (USD)</span>
    <strong>${{order.get_total}}</strong>
</li>
</ul>
<!-- Cart -->

{% if DISPLAY_COUPON_FORM %}
<!-- Promo code -->
<form class="card p-2" action="{% url 'store:add-coupon' %}" method="post">
    {% csrf_token %}
    <div class="input-group">
        {{ CouponForm.code }}
        <!-- <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2"> -->
        <div class="input-group-append">
        <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
        </div>
    </div>
</form>
<!-- Promo code -->
{% endif %}

</div>

templates/order_summary.html
{% extends 'base.html' %} 

{% block content %}
<!--Main layout-->
<main>
  <div class="container">
    <h2>Order Summary</h2>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Item title</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col">Total Item Price</th>
        </tr>
      </thead>
      <tbody>
        {% for order_item in object.items.all %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{order_item.item.title}}</td>
          <td>{{order_item.item.price}} <del>{{order_item.get_total_discount_item_price}}</del> </td>
          <td>
            <a href="{% url 'store:remove-single-item-from-cart' order_item.item.slug %}" style="text-decoration: none; color:black;">
              <!-- <i class="bi bi-dash-circle"></i> -->
              -
              {{ order_item.quantity }}
            <a href="{% url 'store:add-to-cart' order_item.item.slug %}" style="text-decoration: none; color:black;">
              <!-- <i class="bi bi-plus-circle"></i> -->
              +
          </td>
          <td>$
            {% if order_item.item.discount_price %}
              {{order_item.get_total_discount_item_price}}
              <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
            {% else %}
              {{order_item.get_total_item_price}}
            {% endif %}
            <a style='color: red;' href="{% url 'store:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="5">Your cart is empty</td>
          <td colspan="4">
            <a class="btn btn-info" href="{% url 'store:home' %}"> continue shoping </a>
          </td>
        </tr>
        {% endfor %}

        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        
        {% if object.get_total %}
        <tr>
          <td colspan=4><b> Order Total</b></td>
          <td><b> ${{object.get_total}} </b></td>
        </tr>
        <tr>
          <td colspan="4">
            <a class="btn btn-info" href="{% url 'store:home' %}"> continue shoping </a>
            <a class="btn btn-warning mx-2" href="{% url 'store:checkout' %}"> Proceed to checkout </a>
          </td>
        </tr>
        {% endif %}
      </tbody>
    </table>
  </div>
</main>
<!--Main layout-->
{% endblock content %}

templates/product.html
{% extends 'base.html' %}


{% block content %}
    <div class="container my-3">

      <div class="row">

        <div class="col-md-6 mb-4 shadow-sm" >
          <img src="{{object.image.url}}" class="img-fluid" alt="" style=" object-fit: cover;">
        </div>

        <div class="col-md-6 mb-4">
          <div class="p-4">
            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{object.get_category_display}}</span>
              </a>
            </div>

            <p class="">
              {% if object.discount_price %}
                <span class="mr-1">
                  <del>${{object.price}}</del>
                </span>
                <span>${{object.discount_price}}</span>
              {% else %}
                <span>${{object.price}}</span>
              {% endif %}
            </p>

            <p class="font-weight-bold">Description</p>

            <p>{{object.description}}</p>

              <a href="{{object.get_add_to_cart_url}}" class="btn btn-primary btn-md my-0 p">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>

              <a href="{{object.get_remove_from_cart_url}}" class="btn btn-danger btn-md my-0 p">
                Remove from cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>

          </div>
        </div>

      </div>

    </div>
{% endblock content %}
  

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}