core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('store.urls', namespace="store")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

store/urls.py
from django.urls import path 
from .views import (CheckoutView, ItemDetail, HomeView, add_to_cart, 
                    remove_from_cart, OrderSummaryView, remove_single_item_from_cart,
                    PaymentView, AddCouponView, RequestRefundView, CategoryDetail,
                    LandingPage
)
app_name = "store"

urlpatterns = [
    path("", LandingPage, name="landpage"),
    path("home/", HomeView.as_view(), name="home"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("order-summary/", OrderSummaryView.as_view(), name="order-summary"),
    path("product/<slug>", ItemDetail.as_view(), name="product"),
    path("add-to-cart/<slug>", add_to_cart, name="add-to-cart"),
    path("add-coupon", AddCouponView.as_view(), name="add-coupon"),
    path("remove-from-cart/<slug>", remove_from_cart, name="remove-from-cart"),
    path("remove-single-item-from-cart/<slug>", remove_single_item_from_cart, name="remove-single-item-from-cart"),
    path("payment/<payment_option>", PaymentView.as_view(), name="payment"),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),

    path('categorydetail/<slug>', CategoryDetail, name='categorydetail')
]

templates/components/footer.html
<!-- Footer-->
<footer class="bg-dark pt-5 pb-3">
    <div class="container">
        <div class="row">
            <div class="footer-col">
                <h4 class="">company</h4>
                <ul>
                    <li><a href="#">about us</a></li>
                    <li><a href="#">our services</a></li>
                    <li><a href="#">privacy policy</a></li>
                    <li><a href="#">affiliate program</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>get help</h4>
                <ul>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#">shipping</a></li>
                    <li><a href="#">returns</a></li>
                    <li><a href="#">order status</a></li>
                    <li><a href="#">payment options</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>online shop</h4>
                <ul>
                    <li><a href="#">watch</a></li>
                    <li><a href="#">bag</a></li>
                    <li><a href="#">shoes</a></li>
                    <li><a href="#">dress</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>follow us</h4>
                <div class="social-links">
                    <a href="#"><i class="bi bi-facebook"></i></a>
                    <a href="#"><i class="bi bi-twitter"></i></a>
                    <a href="#"><i class="bi bi-instagram"></i></a>
                    <a href="#"><i class="bi bi-linkedin"></i></a>
                </div>
            </div>
        </div>
        <p class="mt-5 text-center text-white">Copyright &copy; Your Website 2022</p>
    </div>
</footer>

templates/components/header.html
{% load static %}

<section class="home">

<div id="carousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-controls">
    <ol class="carousel-indicators">
      <li data-target="#carousel" data-slide-to="0" class="active" style="background-image:url('static/img/nav/slide-1.jpg')"></li>
      <li data-target="#carousel" data-slide-to="1" style="background-image:url('static/img/nav/slide-2.jpg')"></li>
      <li data-target="#carousel" data-slide-to="2" style="background-image:url('static/img/nav/slide-3.jpg')"></li>
      
    </ol>
    <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
     <img src="static/img/nav/left-arrow.svg" alt="Prev"> 
  </a>
  <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
    <img src="static/img/nav/right-arrow.svg" alt="Next">
  </a>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active" style="background-image:url('static/img/nav/slide-1.jpg')">
      <div class="container">
         <h2>I'm Rose</h2>
         <p>Easy Shopping With Us</p>
      </div>
    </div>
    <div class="carousel-item" style="background-image:url('static/img/nav/slide-2.jpg')">
      <div class="container">
         <h2>I'm Jasmine</h2>
         <p>Easy Shopping With Us</p>
      </div>
    </div>
    <div class="carousel-item" style="background-image:url('static/img/nav/slide-3.jpg')">
      <div class="container">
         <h2>I'm Ruby</h2>
         <p>Easy Shopping With Us</p>
      </div>
    </div>
  </div>
</div>

</section>

templates/components/navbar.html
{% load cart_template_tags %}

<nav
class="navbar navbar-expand-lg navbar-light shadow-sm bg-light"
>
  <div class="container">
    <!-- Brand -->
    <a class="navbar-brand" href="/">
      <strong class="blue-text">STORE</strong>
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        <!-- <li class="nav-item active">
            <a class="nav-link" href="{% url 'store:home' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'store:home' %}">All Products</a>
          </li>
      </ul>

      <!-- Right -->

      <ul class="navbar-nav ms-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a href="{% url 'store:order-summary' %}" class="nav-link btn btn-outline-dark">
                <i class="bi-cart-fill me-1"></i>
                Cart
                <span class="badge bg-dark text-white ms-1 rounded-pill">{{request.user|cart_item_count}}</span>
            </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_logout' %}">
            <span class="clearfix d-sm-inline-block"> Logout </span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}">
            <span class="clearfix d-sm-inline-block"> Login </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_signup' %}">
            <span class="clearfix d-sm-inline-block"> Signup </span>
          </a>
        </li>
        {% endif %}
      </ul>


      

    </div>
  </div>
</nav>

templates/components/scripts.html
{% load static %}

<!-- Bootstrap core JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<!-- Swiper JS -->
<script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>

<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>